version: '3'
services:
  CAMUNDA:    
    image: camundabpm-docker
    container_name: aot_foi_cc_camunda_bpm     
    build:
      context: ./      
      dockerfile: bpmwf/dockerfile
    ports:
      - "6401:8080"    
    networks:
      services-network:
        aliases:
          - camundabpmnw
  BACKEND:
    build:
      context: ./      
      dockerfile: backend/dockerfile
    image: ccbackendimage
    container_name: aot_foi_cc_backend
    depends_on: 
      - postgresqldb     
    networks:
      services-network:
        aliases:
          - backendnw
    ports:
      - 6402:6402
    environment:
      - DATABASE_URL=postgresql://docker:docker@postgresqldb:5432/docker
      - FLASK_ENV:DEV
  FRONTEND:
    build:
      context: ./      
      dockerfile: frontend/Dockerfile      
      args:
        - API_BASE_URL=http://localhost:6402/
        - KEYCLOAK_URL=https://iam.aot-technologies.com/auth/
        - KEYCLOAK_REALM=foirealm
        - KEYCLOAK_CLIENT=foiclientfe
        - KEYCLOAK_CLIENT_SECRET=fdf3be98-6dfa-4a5a-a0fe-ef644ffbe106
        - CAMUNDAENGINEBASEURL=http://localhost:6401/engine-rest
        - CAMUNDABPMNFILE=FOICCBPMNFILE1
    image: ccfrontendimage
    container_name: aot_foi_cc_frontend   
    ports:
      - 6403:6403
    depends_on:
      - BACKEND
    networks:
      services-network:
        aliases:
          - frontendnw
  postgresqldb:
    image: postgres
    container_name: aot_foi_cc_db_pg
    ports:
      - "6404:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    networks:
      services-network:
        aliases:
          - db   
volumes:
  dbdata:
networks:
  services-network:
    name: services-network
    driver: bridge
