version: '3'
services:  
  BACKEND:
    build:
      context: ./      
      dockerfile: backend/dockerfile
    image: ccbackendimage
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:password@foicccb.cwpb3horhlgp.us-east-2.rds.amazonaws.com:5432/postgres
      - FLASK_ENV:DEV
  FRONTEND:
    build:
      context: ./      
      dockerfile: frontend/Dockerfile
      args:
        - API_BASE_URL=http://localhost:5000/
        - KEYCLOAK_URL=https://iam.aot-technologies.com/auth/
        - KEYCLOAK_REALM=foirealm
        - KEYCLOAK_CLIENT=foiclientfe
        - KEYCLOAK_CLIENT_SECRET=fdf3be98-6dfa-4a5a-a0fe-ef644ffbe106
    image: ccfrontendimage    
    ports:
      - 8080:8080
    depends_on:
      - BACKEND           
volumes:
  dbdata:
