version: '3'
services:  
  BACKEND:
    build:
      context: ./      
      dockerfile: backend/dockerfile
    image: ccbackendimage
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:password@foicccb.cwpb3horhlgp.us-east-2.rds.amazonaws.com:5432/postgres
      - FLASK_ENV:DEV
  FRONTEND:
    build:
      context: ./      
      dockerfile: frontend/Dockerfile
    image: ccfrontendimage
    ports:
      - 8080:8080
    depends_on:
      - BACKEND           
volumes:
  dbdata:
