# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.9
EXPOSE 6402

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

COPY backend/. /app
WORKDIR /app
RUN pip3 install --no-cache-dir -r requirements.txt

# Creates a non-root user and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
#RUN useradd appuser && chown -R appuser /app
#USER appuser

CMD ["flask", "run", "-h", "0.0.0.0", "-p", "6402"]