"""empty message

Revision ID: 07f4601bef48
Revises: 
Create Date: 2021-03-23 20:43:09.806919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07f4601bef48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Requests',
    sa.Column('requestid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('createdby', sa.String(length=25), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.Column('userid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('transactionid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('requestid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Requests')
    # ### end Alembic commands ###
